name: paws_for_home
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.11+12

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  dio: ^5.4.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  flutter_svg: ^2.0.10+1
  flutter_staggered_grid_view: ^0.7.0
  icons_flutter: ^0.0.5
  intl: ^0.19.0
  url_launcher: ^6.2.5
  logger: ^2.6.0
  go_router: ^13.2.2
  share_plus: ^7.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4
  dropdown_search: ^5.0.0
  webview_flutter: ^4.7.0
  http: ^1.2.0
  html: ^0.15.4
  in_app_update: ^4.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF"